FROM keymetrics/pm2:10-alpine

# Bundle files
COPY api api/
COPY constants constants/
COPY routes routes/
COPY app.ts .
COPY env.ts .
COPY index.ts .
COPY middlewares.ts .
COPY package.json .
COPY pm2.json .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Expose the listening port
EXPOSE 3333

# Show current folder structure in logs
RUN ls -al -R

# CLI command: docker build --build-arg APP_ENV=[DEV or PROD] --tag GrubberApi
# CLI command: docker run --publish 80:3333 --detach --name ga GrubberApi
CMD [ "pm2-runtime", "start", "pm2.json", "--only", $APP_ENV ]